spring:

  datasource:
    url: jdbc:postgresql://db:5432/grocery_db1
    username: postgres
    password: postgres
    initialization-mode : always
  jpa:
    hibernate:
      ddl-auto: create-drop

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    profiles:
      active: dev